ALTER TABLE publishes
ADD COLUMN IF NOT EXISTS metrics_ctr DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS metrics_retention_3s DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS metrics_avg_watch_duration_sec DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS metrics_completion_rate DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS last_analyzed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS optimization_status TEXT,
ADD COLUMN IF NOT EXISTS optimization_variants JSONB,
ADD COLUMN IF NOT EXISTS optimization_updated_at TIMESTAMPTZ;
